version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mongo-primary
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_net

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express-primary
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASIC_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASIC_PASS}
    ports:
      - "8081:8081"
    networks:
      - mongo_net

volumes:
  mongo_data:

networks:
  mongo_net:
    driver: bridge
